/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package social.tangent.mobile.api.entities

import kotlinx.serialization.*

import social.tangent.mobile.api.entities.Status

/**
 * Represents the tree around a given status. Used for reconstructing threads of statuses.
 * @see https://docs.joinmastodon.org/entities/context/
 */
@Serializable
data class Context(

  /**
   * Description: Parents in the thread.
   * Type: Array of Status
   * Version history: Added in 0.6.0
   */
  val ancestors: List<Status>,

  /**
   * Description: Children in the thread.
   * Type: Array of Status
   * Version history: Added in 0.6.0
   */
  val descendants: List<Status>
)
