/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package social.tangent.mobile.api.entities

import kotlinx.serialization.Serializable

/**
 * Represents a mention of a user within the content of a status.
 * @see https://docs.joinmastodon.org/entities/mention/
 */
@Serializable
data class Mention(

    /**
     * Description: The account id of the mentioned user.
     * Type: String (cast from an integer, but not guaranteed to be a number)
     * Version history: Added in 0.6.0
     */
    val id: String,

    /**
     * Description: The username of the mentioned user.
     * Type: String
     * Version history: Added in 0.6.0
     */
    val username: String,

    /**
     * Description: The webfinger acct: URI of the mentioned user.
     * Equivalent to username for local users, or username@domain for remote users.
     * Type: String
     * Version history: Added in 0.6.0
     */
    val acct: String,

    /**
     * Description: The location of the mentioned user's profile.
     * Type: String (URL)
     * Version history: Added in 0.6.0
     */
    val url: String
)
