/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package social.tangent.mobile.api.entities

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Unsure.
 * @see https://docs.joinmastodon.org/entities/report/
 */
@Serializable
data class Report(

    /**
     * The ID of the report
     */
    val id: String,

    /**
     * The action taken in response to the report
     */
    @SerialName("action_taken")
    val actionTaken: String
)
