/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package social.tangent.mobile.api.entities

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a status that will be published at a future scheduled date.
 * @see https://docs.joinmastodon.org/entities/scheduledstatus/
 */
@Serializable
data class ScheduledStatus(

    /**
     * Description: ID of the scheduled status in the database.
     * Type: String (cast from an integer but not guaranteed to be a number)
     * Version history: Added in 2.7.0
     */
    val id: String,

    /**
     * Description: ID of the status in the database.
     * Type: String (ISO 8601 Datetime)
     * Version history: Added in 2.7.0
     * @DateTime
     */
    @SerialName("scheduled_at")
    @Serializable(with = kotlinx.datetime.serializers.InstantIso8601Serializer::class)
    val scheduledAt: kotlinx.datetime.Instant
)
